name: CI

on:
  release:
    types: [created]
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Lint with rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt

      - name: Lint with clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features

      - name: Test with cargo
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          toolchain: nightly

  build:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual env
        run: |
          python -m venv ../venv
          ../venv/bin/python -m pip install -U pip wheel

      - name: Use virtual env path (*nix)
        if:  matrix.os != 'windows-latest'
        run: echo "$(realpath ../venv/bin)" >> $GITHUB_PATH

      - name: Use virtual env path (Windows)
        if:  matrix.os == 'windows-latest'
        run: echo "$(realpath ../venv/bin)" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install dependencies
        run: python -m pip install maturin pytest

      - name: Build Python package
        run: maturin develop --release
        env:
          VIRTUAL_ENV: ../venv

      - name: pytest
        run: pytest
